pipeline {
    agent any 

    stages {
        stage('Checkout & Sync') {
            steps {
                checkout scm
                echo "✅ Webhook Received"
            }
        }

        stage('Build Maintenance Image') {
            steps {
                dir('day12-storage-automation') {
                    // Build the image and name it 'storage-cleaner'
                    sh 'docker build -t storage-cleaner:latest .'
                }
            }
        }

        stage('Run Cleanup Container') {
            steps {
                echo '🚀 Launching the Maintenance Container...'
                // --rm deletes the container automatically after it finishes the job
                // -v /tmp:/tmp allows the container to 'reach out' and clean your laptop's /tmp folder
                sh 'docker run --rm -v /tmp:/tmp storage-cleaner:latest'
            }
        }
    }

    post {
        success {
            echo "🏆 Day 12 SUCCESS: Container ran and storage is healthy."
        }
    }
}
