pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps {
                echo '🚚 Code is ready!'
                sh 'ls -R'
            }
        }
        stage('Lint & Test') {
            steps {
                dir('day2-system-monitor') {
                    echo '🔍 Checking Python syntax...'
                    sh 'python3 -m py_compile monitor.py'
                }
            }
        }
        stage('Execute') {
            steps {
                dir('day2-system-monitor') {
                    echo '🚀 Running the System Monitor...'
                    sh 'python3 monitor.py'
                }
            }
        }
    }
}